### ISSUE TITLE
[Android]Microphone stops working after 1 minute of the app going to background

### ISSUE THREAD

**Issue by osm-y** [aws-samples/amazon-chime-sdk-flutter-demo#4]
On Android, microphone stops working after 1 minute of the app going to background. After 1 minute has elapsed, the other party's voice is still audible.

**Comment by georgezy-amzn** [comment]
Hi @osm-y,

Sorry for the delayed response. We'll look into the root cause. Could you provide the details on:
 1. Device: [e.g. Samsung Galaxy S22]
 2. OS: [e.g. Android 13]

Thanks!

**Comment by osm-y** [comment]
Hi @georgezy-amzn 

Thanks for the reply. I found a similar issue in the Android SDK and fixed it with that.
https://github.com/aws/amazon-chime-sdk-android/issues/339#issuecomment-954982389

This issue is closed.

Thanks
